name: Medical Data Warehouse CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-postgres ultralytics pandas sqlalchemy psycopg2-binary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create Dummy Profile
      run: |
        mkdir -p ~/.dbt
        echo "kara_dbt:
          target: dev
          outputs:
            dev:
              type: postgres
              host: localhost
              user: dummy
              password: dummy
              port: 5432
              dbname: dummy
              schema: public
              threads: 1" > ~/.dbt/profiles.yml

    - name: dbt Parse
      run: |
        cd kara_dbt
        dbt parse --profiles-dir ~/.dbt